### ISSUE TITLE
请问如何使用

### ISSUE THREAD

**Issue by taotaolin** [playwithblockchain/baidu-pet-chain-buyer#1]
装了没有任何变化呃。。

**Comment by nanguoyu** [comment]
@taotaolin 你下的是源码吗？chrome开发者模式加载已解压的拓展程序。

**Comment by xuyuji9000** [comment]
翻墙安装chrome插件。

**Comment by taotaolin** [comment]
@nanguoyu @xuyuji9000 我是chrome已经装好了插件，还是没反应。直接商店装的

**Comment by gdmec07150737** [comment]
是打开控制台可以看到的吧！

**Comment by xsnonline** [comment]
有没有日志什么的？让我看到他的运行状态？

**Comment by taotaolin** [comment]
@xsnonline F12控制台Console可以看见操作

**Comment by bingFly** [comment]
有没有不翻墙可以运行的？

**Comment by tabalt** [comment]
请参考WIKI：
https://github.com/playwithblockchain/baidu-pet-chain-buyer/wiki
