### ISSUE TITLE
加验证码了老铁

### ISSUE THREAD

**Issue by FB208** [playwithblockchain/baidu-pet-chain-buyer#16]

**Comment by cheneydc** [comment]
扎心得勒

**Comment by diong** [comment]
明天是不是价格自动识别验证码

**Comment by cheneydc** [comment]
不过验证码是不是有问题  手动的时候一直提示验证码过期

**Comment by LightGal** [comment]
期待

**Comment by demonclan** [comment]
啥时候加识别验证码哦！？嗯？？

**Comment by pangyiren** [comment]
不一定非要自动识别验证码，如果可以将验证码弹出，手动输入，速度也可以比纯手动提升很多。

**Comment by liuying1001** [comment]
有验证码了，新需求

**Comment by Blz-Galaxy** [comment]
改了下，目前只支持手工输入，哪位有好用的前端OCR组件哦？

**Comment by tabalt** [comment]
支持验证码的版本有啦

**Comment by liuying1001** [comment]
厉害了，明天试试




| |
刘颖
邮箱：liuying31195@126.com
|

签名由 网易邮箱大师 定制

在2018年02月09日 00:35，tabalt 写道：

支持验证码的版本有啦
