### ISSUE TITLE
读取不到配置信息

### ISSUE THREAD

**Issue by FB208** [playwithblockchain/baidu-pet-chain-buyer#2]
首先感谢分享
问题：
修改了命中策略但是读取不到
![image](https://user-images.githubusercontent.com/8197476/35784861-0e90d16c-0a57-11e8-860b-59c77909954f.png)

![image](https://user-images.githubusercontent.com/8197476/35784872-1d4fd93c-0a57-11e8-95c7-d1c01677195d.png)

**Comment by SeanChao** [comment]
+1

**Comment by clay4444** [comment]
+1

**Comment by xiaolongwuhpu** [comment]
+1

**Comment by hanxu317317** [comment]
看了一下代码. optione下写入的localstorag在首页跨域了读不到.

**Comment by tabalt** [comment]
新版已经修复
