### ISSUE TITLE
建议增加异步缓存验证码

### ISSUE THREAD

**Issue by huangweijun** [playwithblockchain/baidu-pet-chain-buyer#20]
先调用申请验证码接口，让用户人工识别seed和Captcha一一对应缓存起来，遇到符合条件购买就自动使用{seed,captcha}这样可以大部分时候解放用户并且加快购买速度

**Comment by tabalt** [comment]
测试过这样可行吗？ {seed,captcha} 有没有效期？

**Comment by huangweijun** [comment]
完全可以，有效期没有具体测过，我输入个二十来个，可以用半个到一个小时

**Comment by huangweijun** [comment]
https://github.com/vman1900/laicigou-browser-script

**Comment by huangweijun** [comment]
可以参考这个的逻辑

**Comment by tabalt** [comment]
你的脚本好坑啊，测试执行了一把，我之前2000买的狗狗300卖了。。 
不过你这个事先储备验证码的想法不错

**Comment by Yangk030208** [comment]
验证码的地方一直是空的。没有加载出来。

**Comment by Yangk030208** [comment]
难道就我一个有这个问题？

**Comment by tabalt** [comment]
@Yangk030208   验证码为空是接口的问题

**Comment by tabalt** [comment]
2.1版已新增提前打码功能，请各位试用
