### ISSUE TITLE
插件页面不在前台，不能自动提交订单

### ISSUE THREAD

**Issue by CodingPub** [playwithblockchain/baidu-pet-chain-buyer#30]
插件页面不在前台时，不能自动提交订单，这个能优化吗

**Comment by CodingPub** [comment]
补充：如果是插件页面单独一个窗口，即使不是激活窗口，也能正常提交订单。但是，如果是一个窗口多个 Tab，如果插件页面不是激活 Tab，不能正常提交表单。

**Comment by austinchenji** [comment]
一直在后台运行也会有打码超时的问题。我感觉这个意义不大。

**Comment by tabalt** [comment]
没注意到这种情况，如果确实有的话，应该是Chrome的机制限制了，开两个窗口吧

**Comment by DaZiYuan** [comment]
`  setTimeout(function(){
                $('#buyModalCenter').modal('hide');
            }, 1*1000);`

好像是bootstrap的bug。页面没激活，这个窗口关闭不了
#https://github.com/twbs/bootstrap/issues/7918
