### ISSUE TITLE
设置了买入配置，并保存了起来，为什么购入还是已不一样的价格购入了？

### ISSUE THREAD

**Issue by LeachZhou** [playwithblockchain/baidu-pet-chain-buyer#9]
设置了普通100以下，却以950买了普通，设置了卓越500以下，却以4000买了卓越

**Comment by icesunx** [comment]
这么夸张嘛……

**Comment by hanxu317317** [comment]
代码上看了...不会出现这的问题~~感觉可能是百度服务器乱了.

**Comment by thisisnotmea** [comment]
不知道何时能修复好呢？

**Comment by slqx** [comment]
楼主中招了。
这是一个反向策略。
步骤1. 卖出一个低价狗。
步骤2. 秒撤回（撤回前，大部分抢购脚本可能已经抓到了该狗的petid）
步骤3. 刚才卖的狗改高价再次卖出
步骤4. 等待步骤2时用脚本的人去买你的高价狗吧。
几天试了几次，成功率不低，不过也失手的情况。

问题的关键在于，按价格查询和购买不在一个事务，同一只狗，查询的时候和买的时候，价格确实可能不一样。

**Comment by kunwang** [comment]
我设置的50普通，买到一直普通花了4000😄

**Comment by LeachZhou** [comment]
我又以999买了一只普通狗...

**Comment by fox000002** [comment]
反向策略失败，撤不回😄

**Comment by wheelBL** [comment]
这说明需要在买入的时候再确认一次。

**Comment by jiansing** [comment]
5559买了普通，有谁比我更惨的吗...

**Comment by zhaoxiuyu** [comment]
@jiansing  为什么有那么多的微分

**Comment by tabalt** [comment]
百度修了这个问题了吗，还有遇到类似情况吗?

**Comment by wuyanzu01** [comment]
是的呢。
